In [1]:
import json
import os
import pandas as pd

In [2]:
with open("../../data/prediction_val_sub01/val_predict_sub01_finetuned_fixed_id.json", "r") as f_q:
    answers_val = json.load(f_q)

In [3]:
val_dataset = pd.read_csv("./vqa_val_sub01.tsv", sep="\t", 
                          names = ["question_id", "image-id", "question", "answer", "labels", "image"])
val_dataset.drop(["labels", "image"], inplace = True, axis=1)
val_dataset["answer"] = val_dataset.apply(
    lambda x: x["answer"].split('|!+')[1] , axis=1)

In [4]:
val_dataset

,question_id,image-id,question,answer
0,67255013,67255,How many cars are on the crosswalk,0 0 cars are on the crosswalk
1,134103008,134103,Are these people wearing helmets,No these people are not wearing helmets
2,478240008,478240,Are the men riding a bicycle,No the men are not riding a bicycle
3,174091008,174091,How many servings of pizza,8 8 servings of pizza
4,151084001,151084,Is the man barefoot,No the man is not barefoot
...,...,...,...,...
22325,359039000,359039,What gender are the children,Male are the children
22326,198733001,198733,Is the guy in mid air,Yes the guy is in mid air
22327,178982001,178982,What city is this,New york is this
22328,68838002,68838,How many bolts are holding the sign onto the b...,4 4 bolts are holding the sign onto the building
22329,310663002,310663,What numbers are visible on the train,2002 are visible on the train

In [25]:
answers_df = pd.DataFrame(answers_val)
joined = answers_df.join(val_dataset.set_index("question_id"),how = "inner", on = "question_id",lsuffix="-generated", rsuffix="-gt")
cols = ["question_id", "image-id", "question", "answer-gt","answer-generated"]
joined = joined[cols]

In [26]:
joined

,question_id,image-id,question,answer-gt,answer-generated
0,67255013,67255,How many cars are on the crosswalk,0 0 cars are on the crosswalk,3 3 cars are on the train viewed in the picture
1,134103008,134103,Are these people wearing helmets,No these people are not wearing helmets,0 are they playing
2,478240008,478240,Are the men riding a bicycle,No the men are not riding a bicycle,This the hand of is human
3,174091008,174091,How many servings of pizza,8 8 servings of pizza,2 2 servings are on the table
4,151084001,151084,Is the man barefoot,No the man is not barefoot,This the hand of is human
...,...,...,...,...,...
22324,359039000,359039,What gender are the children,Male are the children,1st is the book
22325,198733001,198733,Is the guy in mid air,Yes the guy is in mid air,Itch the elephant is scratching its head again...
22326,178982001,178982,What city is this,New york is this,seagulls are flying over the ocean with mounta...
22327,68838002,68838,How many bolts are holding the sign onto the b...,4 4 bolts are holding the sign onto the building,4 4 bolts are on the sign
22328,310663002,310663,What numbers are visible on the train,2002 are visible on the train,0 are visible in this picture

In [27]:
joined.to_csv("../../data/prediction_val_sub01/preditctions_gt_q.csv")

In [28]:
sample_preds = joined.sample(10)
sample_preds

,question_id,image-id,question,answer-gt,answer-generated
9420,322762002,322762,Where is the elephants trunk,The elephants trunk is mouth,tree is a man holding a small red guitar
8940,459934000,459934,Which structure is crooked,Toilet structure is crooked,2nd from left person has blonde hair
13036,223243001,223243,What game is he playing,Baseball is he playing,Uphill where are they going
21870,810001,810,What kind of sandwich is this,Blt sandwich is this,2nd from left person has blonde hair
9263,248396000,248396,What is the color of the cones,The color of the cones is orange,2 orange and red is fire
19292,298172003,298172,How would a food critic describe this cuisine,Healthy a food would critic describe this cuisine,a food line where people are getting hotdogs a...
12974,391371006,391371,Is there a hat on the bench,No there is not a hat on the bench,Island is in the background
16170,361481001,361481,Is this a healthy dish,Yes this is a healthy dish,Uphill where are they going
12796,144870002,144870,Which room is this,Bedroom room is this,2nd from left person has blonde hair
8797,19087002,19087,Is there a stop sign,No there is not a stop sign,traffic signs on top of poles directs traffic

In [29]:
sample_preds.to_latex("sapmle_preds.tex", index=False, columns = ["question", "answer-gt","answer-generated"])

/tmp/ipykernel_13327/2943583858.py:1: FutureWarning: In future versions `DataFrame.to_latex` is expected to utilise the base implementation of `Styler.to_latex` for formatting and rendering. The arguments signature may therefore change. It is recommended instead to use `DataFrame.style.to_latex` which also contains additional functionality.
  sample_preds.to_latex("sapmle_preds.tex", index=False, columns = ["question", "answer-gt","answer-generated"])